### ISSUE TITLE
Support for private packages

### ISSUE THREAD

**Issue by n0n3br** [pascalgn/npm-publish-action#12]
I´m trying to publish a package with my username tag but I get an error:

error Couldn't publish package: "https://registry.yarnpkg.com/@n0n3br%2fsvelte-hash-spa-router: You must sign up for private packages"

Maybe you could implement support for the --access public modifier in the npm publish command to resolve this.

**Comment by pomber** [comment]
I'm having the same problem. I think the issue's title should be "Support scoped packages". Or maybe, add support for `yarn publish` args.

**Comment by ydennisy** [comment]
I believe you can just add the following to your `package.json`:

```
  "publishConfig": {
    "access": "public"
  },
```

**Comment by pascalgn** [comment]
I think this is fixed now, using the configuration options suggested above. However, feel free to reopen this or create a new issue if you disagree or if there are any other problems! 👍
