### ISSUE TITLE
Add context output after run

### ISSUE THREAD

**Issue by GreenDjango** [pascalgn/npm-publish-action#20]
For link other actions, it would be useful to have a output to know if is a new version and if the new tag is created.

eg: 
- `changed` : either "true" or "false", indicates whether the version has changed.
- Can access the value like this :  `steps.ID.outputs.changed`.

Know it's possible with ``process.stdout.write(`::set-output name=changed::${ some_value }\` + os.EOL)``.

**Comment by pascalgn** [comment]
Agree! Do you like to create a PR for this?
