### ISSUE TITLE
[clone] Support for private packages #12

### ISSUE THREAD

**Issue by gameolive-studio** [pascalgn/npm-publish-action#24]
Unfortunately the fix is not working

> Referring to  https://github.com/pascalgn/npm-publish-action/issues/12#issuecomment-650740650
> 
> I believe you can just add the following to your package.json:
> ```
>   "publishConfig": {
>     "access": "public"
>   },
> ```
> 

I am still getting 
![image](https://user-images.githubusercontent.com/47254525/92645560-52466880-f2e5-11ea-8958-37f388d13936.png)

**Comment by stekyne** [comment]
I'm also having issues publishing a private package for an org.

**Comment by stekyne** [comment]
After some investigating, yarn doesn't even support this command so no surprise.
https://github.com/yarnpkg/yarn/issues/5310

Maybe should use NPM for publishing.

**Comment by pascalgn** [comment]
Yes, looks like the solution in #12 won't work. I think another suggestion was to support configurable arguments for `yarn publish`. Do you maybe want to try it and create a PR?

**Comment by gameolive-studio** [comment]
a quick question to understand, At https://github.com/pascalgn/npm-publish-action/blob/master/index.js#L127 why we are doing yarn publish may be it makes sense to use ```npm publish``` instead

**Comment by pascalgn** [comment]
You can now use the new `PUBLISH_ARGS` option, like this:

```yaml
      with:
        publish_args: "--access private"
```

Does this help?
