### ISSUE TITLE
How to publish multiple packages to NPM?

### ISSUE THREAD

**Issue by ljwagerfield** [pascalgn/npm-publish-action#33]
My repository contains two packages with matching version numbers:

- `./foo`

- `./foo-example`

I would like to publish both to NPM.

However, I cannot simply include the `npm-publish-action` twice (once for each working directory) as the 2nd will always be skipped, as the git tag will already exist by that point, due to the first action having created it.

What's the best solution here?

**Comment by pascalgn** [comment]
I think the best option could be to add a new configuration option to this action like `create_tag` which accepts true (default) or false. Then you can have 2 instances of the action, where the first one has `create_tag: false`

Do you want to create a PR for this?

**Comment by ljwagerfield** [comment]
Sure, how about this:

https://github.com/pascalgn/npm-publish-action/pull/34

**Comment by pascalgn** [comment]
I think this is fixed now. However, feel free to reopen this or create a new issue if you disagree or if there are any other problems! 👍
