### ISSUE TITLE
NPM Publish action doesn't work when using 2FA

### ISSUE THREAD

**Issue by jfix** [pascalgn/npm-publish-action#47]
I have one-time passwords enabled in order to publish npm packages as [recommended by NPM](https://docs.npmjs.com/about-two-factor-authentication).

When trying to use the `npm-publish-action` I receive this error message:

```
error Couldn't publish package: "Can't answer a question unless a user TTY"
```

When running `npm publish` manually on the command line, I get challenged for the OTP:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/170240/206856604-48064979-199e-43a0-8120-2423fefa8af0.png">

Is there anything that can be done to integrate OTPs in this action?

**Comment by jonmbake** [comment]
You have to generate a new NPM access token and select the _Automation_ type, which will not require OTP:
<img width="729" alt="Screenshot 2023-03-19 at 5 40 55 PM" src="https://user-images.githubusercontent.com/865534/226214804-b3b9ec6e-dcef-4dc6-9140-a635589ef567.png">

**Comment by jfix** [comment]
thanks @jonmbake that worked great!
