### ISSUE TITLE
tag_name and tag_message

### ISSUE THREAD

**Issue by yawetse** [pascalgn/npm-publish-action#7]
Hi @pascalgn first of all, great action! I'm switching over from travis to GH Actions, I was wondering if you could provide an example of how to pass the tag_name and tag_message via the commit ?

Thanks

**Comment by pascalgn** [comment]
I think (hope) this has been clarified now in the README:

>Now, when someone changes the version in `package.json` to 1.2.3 and pushes a commit with the message `Release 1.2.3`, the `npm-publish` action will create a new tag `v1.2.3` and publish the package to the npm registry.

If you need additional help, feel free to reopen this!
