### ISSUE TITLE
Run fails with "No commit found for version: x.x.x"

### ISSUE THREAD

**Issue by Zhouzi** [pascalgn/npm-publish-action#9]
I might be missing something but when a commit that is not a release is pushed, the run fails with:

> No commit found for version: x.x.x

This marks the repository's latest run as failed and I receive an email. That doesn't seem like an error to me, it's just a commit not to take into consideration.

Is there anything special to configure to silence those failures?

**Comment by EdwinOtten** [comment]
I started using this Action today and immediately run into this issue. @Zhouzi thanks for submitting a fix so quickly!! 👍
